{{- if .Values.efsStorage.enabled -}}
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: {{ .Values.efsStorage.className }}
provisioner: {{ .Values.efsStorage.provisioner }}
parameters:
  provisioningMode: efs-ap
  fileSystemId: {{ .Values.efsStorage.fileSystemId }}
  directoryPerms: "700"
  gidRangeStart: "1001" # optional
  gidRangeEnd: "2000" # optional
  basePath: "/dynamic_provisioning" # optional
  subPathPattern: "${.PVC.namespace}/${.PVC.name}" # optional
  ensureUniqueDirectory: "true" # optional
  reuseAccessPoint: "false" # optional

  {{- end }}