{{ if .Values.tls.createSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "str.fullname" . }}-tls
  labels:
    {{- include "str.labels" . | nindent 4 }}
type: kubernetes.io/tls
data:
  tls.crt: {{ .Values.tls.crt }}
  tls.key: {{ .Values.tls.key }}

{{ end}}