{{- if .Values.localPath.enabled -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shape-files
  labels:
    {{- include "str.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.localPath.className }}
  resources:
    requests:
      storage: 2Gi

  {{- end }}      